SELECT BUY_YOGURT.CART_ID AS CART_ID
FROM 
    (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') AS BUY_YOGURT,
    (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') AS BUY_MILK
WHERE BUY_YOGURT.CART_ID = BUY_MILK.CART_ID
ORDER BY CART_ID